### ISSUE TITLE
lazydocker crashed over the weekend (rename when root cause is found)

### ISSUE THREAD

**Issue by stdedos** [jesseduffield/lazydocker#119]
_I was just about to update for the newest version, when I saw this. It could be #91, but I couldn't match the stacktrace_

**Describe the bug**
_A clear and concise description of what the bug is._

**To Reproduce**
_Steps to reproduce the behavior:_
1. Leave `lazydocker` run over the weekend.
It is possible that it might have happened during one of the (many) re-provisioning commands and I failed to see it in time.

**Expected behaviour**
_A clear and concise description of what you expected to happen._
_Not crash_

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
```bash
$  lsb_release -rd
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
```
 - Lazydocker Version [e.g. v0.1.45]
```bash
Version: commit=572ff63e858150d9cbec6f1ed67ff6d04258c9c0, build date=2019-07-03T14:21:59Z, build source=binaryRelease, version=0.4, os=linux, arch=amd64
```
 - The last commit id if you built project from sources (run : ```git rev-parse HEAD```)

**Additional context**

```go
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1357 +0xae8

goroutine 379181 [semacquire]:
sync.runtime_SemacquireMutex(0xc0003301bc, 0xc000403b00)
        /usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0003301b8)
        /usr/local/go/src/sync/mutex.go:134 +0x109
github.com/jesseduffield/lazydocker/pkg/commands.(*DockerCommand).createClientStatMonitor(0xc000330180, 0xc00e8b0400)
        /go/src/github.com/jesseduffield/lazydocker/pkg/commands/docker.go:181 +0x396
created by github.com/jesseduffield/lazydocker/pkg/commands.(*DockerCommand).MonitorClientContainerStats
        /go/src/github.com/jesseduffield/lazydocker/pkg/commands/docker.go:150 +0x8b

goroutine 378395 [semacquire]:
sync.runtime_SemacquireMutex(0xc0003301bc, 0xc0128cfb00)
        /usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0003301b8)
        /usr/local/go/src/sync/mutex.go:134 +0x109
github.com/jesseduffield/lazydocker/pkg/commands.(*DockerCommand).createClientStatMonitor(0xc000330180, 0xc005dd6400)
        /go/src/github.com/jesseduffield/lazydocker/pkg/commands/docker.go:181 +0x396
created by github.com/jesseduffield/lazydocker/pkg/commands.(*DockerCommand).MonitorClientContainerStats
        /go/src/github.com/jesseduffield/lazydocker/pkg/commands/docker.go:150 +0x8b

goroutine 3528655 [IO wait, 2058 minutes]:
internal/poll.runtime_pollWait(0x7fef97bb08c8, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0f2ca2558, 0x72, 0x8001, 0x8000, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0f2ca2540, 0xc002612000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
os.(*File).read(...)
        /usr/local/go/src/os/file_unix.go:263
os.(*File).Read(0xc01aff9e10, 0xc002612000, 0x8000, 0x8000, 0x0, 0xc01d6be700, 0x40544b)
        /usr/local/go/src/os/file.go:108 +0x70
io.copyBuffer(0x9dcb20, 0xc0003c6500, 0x9dd120, 0xc01aff9e10, 0xc002612000, 0x8000, 0x8000, 0x404f85, 0xc0f2bbc120, 0xc01d6be7b0)
        /usr/local/go/src/io/io.go:402 +0x122
io.Copy(...)
        /usr/local/go/src/io/io.go:364
os/exec.(*Cmd).writerDescriptor.func1(0xc0f2bbc120, 0xc01d6be7b0)
        /usr/local/go/src/os/exec/exec.go:288 +0x63
os/exec.(*Cmd).Start.func1(0xc065852000, 0xc064c9d020)
        /usr/local/go/src/os/exec/exec.go:409 +0x27
created by os/exec.(*Cmd).Start
        /usr/local/go/src/os/exec/exec.go:408 +0x58f

goroutine 423530 [select, 3725 minutes]:
net/http.(*persistConn).readLoop(0xc0014e4a20)
        /usr/local/go/src/net/http/transport.go:1798 +0x95a
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1357 +0xae8

goroutine 3528656 [chan receive, 2058 minutes]:
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).renderContainerLogs.func1.1(0xc00033f860, 0xc000001200, 0xc065852000)
        /go/src/github.com/jesseduffield/lazydocker/pkg/gui/containers_panel.go:195 +0x38
created by github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).renderContainerLogs.func1
        /go/src/github.com/jesseduffield/lazydocker/pkg/gui/containers_panel.go:194 +0x2d6
```

**Comment by jesseduffield** [comment]
Nobody else has reported this issue since this issue was first raised so I'm going to assume it's fixed. If not we'll reopen
