### ISSUE TITLE
Not able to install in windows

### ISSUE THREAD

**Issue by andybala** [jesseduffield/lazydocker#29]
Hi all,

tried to install on Windows with latest goland install. errors attached, not sure what's going wrong

# go get github.com/jesseduffield/lazydocker
# github.com/jesseduffield/lazydocker/pkg/commands
C:\Users\AHB\go\src\github.com\jesseduffield\lazydocker\pkg\commands\os.go:377:46: cmd.SysProcAttr.Setpgid undefined (type *syscall.SysProcAttr has no field or method Setpgid)
C:\Users\AHB\go\src\github.com\jesseduffield\lazydocker\pkg\commands\os.go:379:10: undefined: syscall.Kill
C:\Users\AHB\go\src\github.com\jesseduffield\lazydocker\pkg\commands\os.go:388:3: unknown field 'Setpgid' in struct literal of type syscall.SysProcAttr

-- andy

**Comment by jesseduffield** [comment]
Would it suffice to run this in WSL? There are some tricky things I would need to fix up to get this to run in windows itself

**Comment by mohamedahmed01** [comment]
@jesseduffield 
It seems this code would allow you to bootstrap windows support but i dont know enough go lang enough to implmement it , would you check it out.
https://blog.csdn.net/fyxichen/article/details/51857864

**Comment by jesseduffield** [comment]
@mohamedahmed01 the issue with that code is that I'm using SetPgid so that I can group child processes of a process I run. An example is `docker-compose logs` which itself spawns one process for each service, all of which print to stdout. I give them all the same process group id so that I can kill the group when I want to show the output of some other command. By just returning nil I'd be losing that functionality.

from that link:
```
func SetPgid(pid, pgid int) error {
	return nil
}
```

I believe this is the only real think preventing windows from working, so a proper solution may not be too hard to achieve. Something along the lines of looking at the process table to find all descendants of the process we want to kill could suffice.

**Comment by jenyayel** [comment]
After installing it in WSL and starting, it crashes:
```
panic: runtime error: invalid memory address or nil pointer dereference                                                                                       [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8119a1]                                                                                                                                                                                                                                                      goroutine 1 [running]:                                                                                                                                        github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*View).Name(...)                                                                           /go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/view.go:157                                                         github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).switchFocus(0xc000398000, 0xc000314210, 0xc00011a3c0, 0x0, 0x9d6460, 0xc00040a190)                                 /go/src/github.com/jesseduffield/lazydocker/pkg/gui/view_helpers.go:129 +0x71                                                                         github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).returnFocus(0xc000398000, 0xc000314210, 0xc00011a3c0, 0xc00011a3c0, 0x0)                                           /go/src/github.com/jesseduffield/lazydocker/pkg/gui/view_helpers.go:117 +0x7a                                                                         github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).closeConfirmationPrompt(0xc000398000, 0xc000314210, 0x0, 0x0)                                                      /go/src/github.com/jesseduffield/lazydocker/pkg/gui/confirmation_panel.go:33 +0x80                                                                    github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).wrappedConfirmationFunction.func1(0xc000314210, 0xc00011a3c0, 0xc, 0x1)                                            /go/src/github.com/jesseduffield/lazydocker/pkg/gui/confirmation_panel.go:24 +0x41                                                                    github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybinding(...)                                                                  /go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:831                                                          github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc000314210, 0xc00011a3c0, 0xc00051f970, 0xc000303680, 0xc000000388, 0xc000000438)                                                                                                                                                /go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:811 +0x1f9                                                   github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).onKey(0xc000314210, 0xc00051f970, 0x2, 0x0)                                          /go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:759 +0x283                                                   github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).handleEvent(...)                                                                     /go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:482                                                          github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc000314210, 0xc000314210, 0x0)                                            /go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:442 +0x203                                                   github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).Run(0xc000398000, 0x0, 0x0)                                                                                        /go/src/github.com/jesseduffield/lazydocker/pkg/gui/gui.go:299 +0x293                                                                                 github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).RunWithSubprocesses(0xc000398000, 0xc000318a00, 0x0)                                                               /go/src/github.com/jesseduffield/lazydocker/pkg/gui/subprocess.go:20 +0x2f                                                                            github.com/jesseduffield/lazydocker/pkg/app.(*App).Run(...)                                                                                                           /go/src/github.com/jesseduffield/lazydocker/pkg/app/app.go:54                                                                                         main.main()                                                                                                                                                           /go/src/github.com/jesseduffield/lazydocker/main.go:57 +0x819
```

**Comment by lcdessantos** [comment]
I managed to get it working on the Windows 10 (Version 1903) WSL and Docker for Windows. But first I had to do the things instructed in this tutorial (with the exception of the "volume mounts" part): [Setting Up Docker for Windows and WSL to Work Flawlessly](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly).

**Comment by jesseduffield** [comment]
Given that it looks like WSL will do the trick, is there anybody with a strong objection against WSL?

**Comment by Harvzor** [comment]
Is the idea that we run LazyDocker in WSL, and expose the Docker Desktop (which is running in Windows) daemon?

**Comment by vitr** [comment]
> Given that it looks like WSL will do the trick, is there anybody with a strong objection against WSL?
Yes) we should have the same Windows binary as we've got for **lazygit**. I understand if this feature request takes some time, but it will be much appreciated.

**Comment by ofek** [comment]
Yes, I'd greatly appreciate Windows support as well
