### ISSUE TITLE
App crashes after going into the shell and exiting it.

### ISSUE THREAD

**Issue by mjarkk** [jesseduffield/lazydocker#44]
**Describe the bug**
I trying some things in a container but when i exited the container ld crached:  
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x80e9d1]

goroutine 1 [running]:
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*View).Name(...)
	/home/mark/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/view.go:157
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).switchFocus(0xc000334000, 0xc0000d8370, 0x0, 0x0, 0x9d1740, 0xc00040b9f0)
	/home/mark/go/src/github.com/jesseduffield/lazydocker/pkg/gui/view_helpers.go:129 +0x71
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).layout(0xc000334000, 0xc0000d8370, 0xc0000101f8, 0xc00021d8c0)
	/home/mark/go/src/github.com/jesseduffield/lazydocker/pkg/gui/layout.go:281 +0x9b3
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.ManagerFunc.Layout(0xc000314400, 0xc0000d8370, 0x0, 0x8)
	/home/mark/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:387 +0x30
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).flush(0xc0000d8370, 0xc000567de0, 0x8ef8c0)
	/home/mark/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:504 +0x33e
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0000d8370, 0xc0000d8370, 0x0)
	/home/mark/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:412 +0x54
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).Run(0xc000334000, 0x0, 0x0)
	/home/mark/go/src/github.com/jesseduffield/lazydocker/pkg/gui/gui.go:309 +0x293
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).RunWithSubprocesses(0xc000334000, 0xc0002caa50, 0x0)
	/home/mark/go/src/github.com/jesseduffield/lazydocker/pkg/gui/subprocess.go:20 +0x2f
github.com/jesseduffield/lazydocker/pkg/app.(*App).Run(...)
	/home/mark/go/src/github.com/jesseduffield/lazydocker/pkg/app/app.go:54
main.main()
	/home/mark/go/src/github.com/jesseduffield/lazydocker/main.go:54 +0x4fa
```

**To Reproduce**
1. Open ld
2. Go to a container and press `c`
3. Select the `Bash` option
4. `Ctrl + D` or `exit`
5. When `Press enter to ...` shows up press `enter`
6. See error

**Expected behaviour**
Do not crash

**Screenshots**
![image](https://user-images.githubusercontent.com/15320763/60439090-6a672600-9c12-11e9-82b4-05253fb5d859.png)

**Desktop (please complete the following information):**
 - OS: Solus 4 (linux)
 - Lazydocker Version: Latest master
 - The last commit id: 750437d

**Comment by jesseduffield** [comment]
See if this fixes it :) https://github.com/jesseduffield/lazydocker/pull/46
