### ISSUE TITLE
Update version execution error: could not determine host context "default" does not exist

### ISSUE THREAD

**Issue by xyabc120** [jesseduffield/lazydocker#493]
**Describe the bug**
After upgrading from `v0.21.0` to `v0.23.1`, executing the lazydocker command resulted in an error :
`could not determine host context "default" does not exist`
`unable to parse docker host ''`

**To Reproduce**
1. `choco upgrade -y lazydocker` （The first installation was done through 'choco install lazydocker'）
2. `lazydocker --version`

![image](https://github.com/jesseduffield/lazydocker/assets/14323465/9c1f955a-5303-4063-9c9d-e0d932b26542)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Lazydocker Version  v0.23.1

**Comment by mark2185** [comment]
Duplicate of https://github.com/jesseduffield/lazydocker/issues/488.

**Comment by xyabc120** [comment]
The `~/.docker` folder already exists in my directory, and this issue still exists.
I resolved this issue by removing the `currentContext` attribute from the `~/.docker/config.json` file

```diff
# set the property value to an empty string
"currentContext": ""
# or remove entire attribute
- "currentContext": "default"
```

**Comment by alexravenna** [comment]
> The `~/.docker` folder already exists in my directory, and this issue still exists. I resolved this issue by removing the `currentContext` attribute from the `~/.docker/config.json` file
> 
> ```diff
> # set the property value to an empty string
> "currentContext": ""
> # or remove entire attribute
> - "currentContext": "default"
> ```

This solved the issue for me too! Although it never feels good to delete something without even knowing what it does 😅 .

**Comment by Jaap-van-Hengstum** [comment]
I can remove the `currentContext`  and lazydocker starts working again, but I have to do that every time Docker Desktop restarts.

**Comment by mark2185** [comment]
What if you set it to an empty string?

**Comment by Jaap-van-Hengstum** [comment]
> What if you set it to an empty string?

Also when I set it to an empty string. 
Docker Desktop resets the value back to `default` when it starts.

I seem to have two Docker contexts:

<img width="1294" alt="image" src="https://github.com/jesseduffield/lazydocker/assets/1670232/3520aacd-f30a-4e48-b614-a600e6dfdedb">

I don't know exactly what these do. I tried removing the `desktop-linux` context, but that also gets recreated when Docker Deskop restarts.

**Comment by dwvwdv** [comment]
I've encountered the same issue, and @xyabc120's method helps me for now. Is this the only way to go?

**Comment by guss77** [comment]
I have the same issue - with `~/.docker/config.json` having the line `"currentContext": "default"`, `lazydocker` will not start.

Setting `currentContext` to the empty string works around the issue - but then `docker-compose` won't start: 

```
$ lazydocker --version
Version: 0.23.1
Date: 2023-10-13T07:40:28Z
BuildSource: binaryRelease
Commit: 1060e17731c80372335446eabe6a56ba4facd2b3
OS: linux
Arch: amd64
$ lsb_release --codename
Codename:       jammy
$ docker-compose --version
docker-compose version 1.29.2, build unknown
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 80, in main
    command_func = dispatch()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 159, in dispatch
    options, handler, command_options = dispatcher.parse(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/compose/cli/docopt_command.py", line 28, in parse
    command_help, options, command = DocoptDispatcher.get_command_and_options(
  File "/usr/lib/python3/dist-packages/compose/cli/docopt_command.py", line 23, in get_command_and_options
    opt = docopt_full_help(command_help, argv, **options)
  File "/usr/lib/python3/dist-packages/compose/cli/docopt_command.py", line 9, in docopt_full_help
    return docopt(docstring, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docopt.py", line 575, in docopt
    extras(help, version, argv, doc)
  File "/usr/lib/python3/dist-packages/docopt.py", line 485, in extras
    sys.exit()
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 129, in main
    exit_with_metrics(command, log_msg=msg, status=status,
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 147, in exit_with_metrics
    MetricsCommand(command, status=status).send_metrics()
  File "/usr/lib/python3/dist-packages/compose/metrics/client.py", line 40, in __init__
    self.context = context_type or ContextAPI.get_current_context().context_type or 'moby'
AttributeError: 'NoneType' object has no attribute 'context_type'
$ docker-compose -p mtproject ps
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 143, in docker_client
    if not context.is_docker_host():
AttributeError: 'NoneType' object has no attribute 'is_docker_host'
```

Removing the `currentContext` completely makes both `lazydocker` and `docker-compose` work. 

Interestingly, with `currentContext` set to the empty string, `lazydocker` works but does not show all docker-compose containers, and for some docker-compose containers it shows the wrong name.

**Comment by c3cris** [comment]
Same issue. Resolved by editing docker config, but that should not be the solution

**Comment by RollsChris** [comment]
same issue for me :( removing currentContext  mkaes lazydocker work but then it gets its added back when restarting docker desktop.. making it unusable

**Comment by RollsChris** [comment]
weirdly if i use "docker context use default" it disappears from the config file and lazydocker works... but still restarting docker adds it back. Something has got twisted here maybe on the docker side. 

Also it might be worth noting switching to desktop-linux context also works

**Comment by hiro345g** [comment]
As a temporary workaround, I was able to get it to work by specifying the DOCKER_HOST environment variable as `DOCKER_HOST="unix:///var/run/docker.sock" lazydocker`.

**Comment by fmanso** [comment]
Any update on this ? How would be the workaround for Windows with Docker Desktop ?

**Comment by peauc** [comment]
@fmanso would you be able to provide a `~/.docker/config.json` that is problematic? I can look onto this issue

**Comment by peauc** [comment]
I have managed to reproduce this issue on Linux, fix it & draft a PR

**Comment by gsenseless** [comment]
my problematic config.json:
```
{
        "auths": {},
        "credStore": "desktop",
        "currentContext": "default",
        "plugins": {
                "-x-cli-hints": {
                        "enabled": "true"
                }
        }
}
```

**Comment by peauc** [comment]
@gsenseless I believe this code has not yet landed on master :).

**Comment by matheustavarestrindade** [comment]
If you are having this problem on windows, i just solved with the cmd: `docker context use default`
