### ISSUE TITLE
Panic: runtime error.

### ISSUE THREAD

**Issue by mybigman** [jesseduffield/lazydocker#7]
Downloaded latest binary. I am running Alpine linux 3.9.4.

Running lazydocker starts fine. But as soon as I touch a key bang this happens-
<img width="654" alt="Screen Shot 2019-06-30 at 5 41 57 pm" src="https://user-images.githubusercontent.com/1289916/60393809-8c9f6c00-9b5e-11e9-9089-e099841868fc.png">
<img width="902" alt="Screen Shot 2019-06-30 at 5 42 57 pm" src="https://user-images.githubusercontent.com/1289916/60393810-8c9f6c00-9b5e-11e9-8c3d-4243e67a983e.png">

After this happens mouse scroll wheel and click spew out all the terminal characters.

**Comment by jesseduffield** [comment]
seems like you had two different errors happening at once. I've hopefully fixed both in the latest release :) https://github.com/jesseduffield/lazydocker/releases/tag/v0.2.2

**Comment by mybigman** [comment]
Using v0.2.3 solves it.

**Comment by eliu** [comment]
I've got the same error here when using lazydocker `0.3`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8119a1]

goroutine 1 [running]:
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*View).Name(...)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/view.go:157
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).switchFocus(0xc000394000, 0xc0002f42c0, 0xc00009d2c0, 0x0, 0x9d6460, 0xc000082190)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/view_helpers.go:129 +0x71
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).returnFocus(0xc000394000, 0xc0002f42c0, 0xc00009d2c0, 0xc00009d2c0, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/view_helpers.go:117 +0x7a
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).closeConfirmationPrompt(0xc000394000, 0xc0002f42c0, 0x0, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/confirmation_panel.go:33 +0x80
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).wrappedConfirmationFunction.func1(0xc0002f42c0, 0xc00009d2c0, 0xc, 0x1)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/confirmation_panel.go:24 +0x41
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybinding(...)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:831
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc0002f42c0, 0xc00009d2c0, 0xc0004ff970, 0xc0004bf0e0, 0xc000000208, 0xc0000002b8)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:811 +0x1f9
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).onKey(0xc0002f42c0, 0xc0004ff970, 0x2, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:759 +0x283
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).handleEvent(...)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:482
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0002f42c0, 0xc0002f42c0, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:442 +0x203
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).Run(0xc000394000, 0x0, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/gui.go:299 +0x293
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).RunWithSubprocesses(0xc000394000, 0xc0002f8a00, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/subprocess.go:20 +0x2f
github.com/jesseduffield/lazydocker/pkg/app.(*App).Run(...)
	/go/src/github.com/jesseduffield/lazydocker/pkg/app/app.go:54
main.main()
	/go/src/github.com/jesseduffield/lazydocker/main.go:57 +0x819
```
