### ISSUE TITLE
Panic runtime error at first running

### ISSUE THREAD

**Issue by hugofcampos** [jesseduffield/lazydocker#70]
**Describe the bug**
Panic error in the first time running on MacOS.

```sh
$ lazydocker
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1413731]

goroutine 1 [running]:
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*View).Name(...)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/view.go:157
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).switchFocus(0xc000068300, 0xc000326160, 0xc0004c12c0, 0x0, 0x15d9080, 0xc0004160f0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/view_helpers.go:129 +0x71
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).returnFocus(0xc000068300, 0xc000326160, 0xc0004c12c0, 0xc0004c12c0, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/view_helpers.go:117 +0x7a
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).closeConfirmationPrompt(0xc000068300, 0xc000326160, 0x0, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/confirmation_panel.go:33 +0x80
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).wrappedConfirmationFunction.func1(0xc000326160, 0xc0004c12c0, 0xc, 0x1)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/confirmation_panel.go:24 +0x41
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybinding(...)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:831
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc000326160, 0xc0004c12c0, 0xc0004ff970, 0xc00006c000, 0xc000000208, 0xc0000002b8)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:811 +0x1f9
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).onKey(0xc000326160, 0xc0004ff970, 0x2, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:759 +0x283
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).handleEvent(...)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:482
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc000326160, 0xc000326160, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:442 +0x203
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).Run(0xc000068300, 0x0, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/gui.go:299 +0x293
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).RunWithSubprocesses(0xc000068300, 0xc0003780a0, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/subprocess.go:20 +0x2f
github.com/jesseduffield/lazydocker/pkg/app.(*App).Run(...)
	/go/src/github.com/jesseduffield/lazydocker/pkg/app/app.go:54
main.main()
	/go/src/github.com/jesseduffield/lazydocker/main.go:57 +0x819
```

**To Reproduce**
1. Install lazydocker by homebrew, following the docs
2. Run lazydocker
3. The alert asking for permission to send anonymous data will be displayed. I accepted that

**Expected behaviour**
I should see the dashboard running. That happened without any problem in the second running.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5 Mojave
 - Lazydocker Version 0.3

**Comment by jesseduffield** [comment]
I think this is fixed in the latest version. Could you give that a try?

**Comment by dawnLyu** [comment]
1
