### ISSUE TITLE
SIGSEGV in declining statistics

### ISSUE THREAD

**Issue by stdedos** [jesseduffield/lazydocker#82]
**Describe the bug**
_A clear and concise description of what the bug is._

**To Reproduce**
1. On first-time installation/open, press `ESC` when it asks enabling diagnostics

**Expected behaviour**
_A clear and concise description of what you expected to happen._
No statistics sent, program continues

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
```bash
$ lsb_release -rd
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
```
 - Lazydocker Version [e.g. v0.1.45]
```
Version: commit=cf31c23fadcc717467318689fc073ecf1bed8031, build date=2019-07-02T00:10:43Z, build source=binaryRelease, version=0.3, os=linux, arch=amd64
```
 - The last commit id if you built project from sources (run : ```git-rev parse HEAD```)

**Additional context**
_Add any other context about the problem here._

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8119a1]

goroutine 1 [running]:
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*View).Name(...)
        /go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/view.go:157
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).switchFocus(0xc000001200, 0xc0000c42c0, 0xc00043d180, 0x0, 0x9d6460, 0xc00049c140)
        /go/src/github.com/jesseduffield/lazydocker/pkg/gui/view_helpers.go:129 +0x71
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).returnFocus(0xc000001200, 0xc0000c42c0, 0xc00043d180, 0xc00043d180, 0x0)
        /go/src/github.com/jesseduffield/lazydocker/pkg/gui/view_helpers.go:117 +0x7a
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).closeConfirmationPrompt(0xc000001200, 0xc0000c42c0, 0x0, 0x0)
        /go/src/github.com/jesseduffield/lazydocker/pkg/gui/confirmation_panel.go:33 +0x80
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).wrappedConfirmationFunction.func1(0xc0000c42c0, 0xc00043d180, 0xc, 0x1)
        /go/src/github.com/jesseduffield/lazydocker/pkg/gui/confirmation_panel.go:24 +0x41
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybinding(...)
        /go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:831
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc0000c42c0, 0xc00043d180, 0xc0001bf970, 0xc000227020, 0xc000000208, 0xc0000002b8)
        /go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:811 +0x1f9
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).onKey(0xc0000c42c0, 0xc000501970, 0x2, 0x0)
        /go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:759 +0x283
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).handleEvent(...)
        /go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:482
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0000c42c0, 0xc0000c42c0, 0x0)
        /go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:442 +0x203
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).Run(0xc000001200, 0x0, 0x0)
        /go/src/github.com/jesseduffield/lazydocker/pkg/gui/gui.go:299 +0x293
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).RunWithSubprocesses(0xc000001200, 0xc000308a00, 0x0)
        /go/src/github.com/jesseduffield/lazydocker/pkg/gui/subprocess.go:20 +0x2f
github.com/jesseduffield/lazydocker/pkg/app.(*App).Run(...)
        /go/src/github.com/jesseduffield/lazydocker/pkg/app/app.go:54
main.main()
        /go/src/github.com/jesseduffield/lazydocker/main.go:57 +0x819

```

**Comment by jesseduffield** [comment]
@stdedos I think this is fixed in the latest version. Could you try that out?

**Comment by stdedos** [comment]
_For everyone else, like the old me: config file is at `~/.config/jesseduffield/lazydocker/config.yml`_

Yep! Good as new!

The fun thing is, that the dialog worked otherwise:
```bash
$ bat ~/.config/jesseduffield/lazydocker/config.yml
───────┬──────────────────────────────────────────────────────
       │ File: ~/.config/jesseduffield/lazydocker/config.yml
───────┼──────────────────────────────────────────────────────
   1   │ reporting: "off"
───────┴──────────────────────────────────────────────────────
$

```

**Comment by jesseduffield** [comment]
good to hear :)

**Comment by jesseduffield** [comment]
I'll update the FAQ about the config locations
