### ISSUE TITLE
lazydocker crashed overnight (rename when root cause is found)

### ISSUE THREAD

**Issue by stdedos** [jesseduffield/lazydocker#91]
**Describe the bug**
_A clear and concise description of what the bug is._

**To Reproduce**
1. Leave `lazydocker` run overnight.
It is possible that it might have happened during one of the (many) re-provisioning commands and I failed to see it in time.

**Expected behaviour**
_A clear and concise description of what you expected to happen._

_Not to crash_

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
```bash
$  lsb_release -rd
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
```
 - Lazydocker Version [e.g. v0.1.45]
```bash
Version: commit=572ff63e858150d9cbec6f1ed67ff6d04258c9c0, build date=2019-07-03T14:21:59Z, build source=binaryRelease, version=0.4, os=linux, arch=amd64
```
 - The last commit id if you built project from sources (run : ```git rev-parse HEAD```)

**Additional context**
_Add any other context about the problem here._

Apologies for the format. That's exactly what my terminal looks like (I needed `stty sane && tput reset` to have a working terminal back)
```go
┌─Status────────────────────────────────────────────────────────────┐┌─Logs - Stats - Config - Top──────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│lazydocker                                                         ││                                                                                                                                      │
└───────────────────────────────────────────────────────────────────┘│ 284 ┼                                                                                                                                │
┌─Containers────────────────────────────────────────────────────────┐│ 256 ┤                                                                                                                                │
│running libvirt 0.01panic: runtime error: index out of range       ││ 227 ┤                                                                                                                                │
│                                                                   ││ 199 ┤                                                                                                                                │
goroutine 342 [running]:                                            ││ 170 ┤                                                                                                                                │
github.com/jesseduffield/lazydocker/pkg/commands.(*Container).PlotGraph(0xc00041d200, 0x0, 0x0, 0x0, 0x937d52, 0xa, 0x942207, 0x1d, 0x933cba, 0x5, ...)                                                     │
│       /go/src/github.com/jesseduffield/lazydocker/pkg/commands/container_stats.go:245 +0x6c5                                                                                                              │
github.com/jesseduffield/lazydocker/pkg/commands.(*Container).RenderStats(0xc00041d200, 0x86, 0x0, 0x0, 0x0, 0x0)                                                                                           │
│       /go/src/github.com/jesseduffield/lazydocker/pkg/commands/container_stats.go:183 +0x1b6                                                                                                              │
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).renderContainerStats.func2(0xc000438300, 0xc0004382a0)                                                                                                   │
│       /go/src/github.com/jesseduffield/lazydocker/pkg/gui/containers_panel.go:150 +0x4d──────────────────────────────────────────────────────────────────────────────────────────────────────────────     │
github.com/jesseduffield/lazydocker/pkg/tasks.(*TaskManager).NewTickerTask.func1(0xc000438300)h42m20.221591887s)                                                                                            │
│       /go/src/github.com/jesseduffield/lazydocker/pkg/tasks/tasks.go:101 +0x10d                                                                                                                           │
github.com/jesseduffield/lazydocker/pkg/tasks.(*TaskManager).NewTask.func1.1(0xc0001b2de0, 0xc000438300, 0xc000277340, 0xc000438420)                                                                        │
│       /go/src/github.com/jesseduffield/lazydocker/pkg/tasks/tasks.go:61 +0x34                                                                                                                             │
created by github.com/jesseduffield/lazydocker/pkg/tasks.(*TaskManager).NewTask.func1                                                                                                                       │
│       /go/src/github.com/jesseduffield/lazydocker/pkg/tasks/tasks.go:60 +0x19f                                                                                                                            │
➜  ~ 0;143;16M0;143;16m0;104;22M0;104;22m0;97;25M0;97;25m
```

**Comment by mjarkk** [comment]
Thanks for the issue,  
Though there is already an issue for this: #76

**Comment by stdedos** [comment]
Same issue again:

```
│<none>                                             <none>          ││         Memory (%): 0.12 (3m42panic: runtime error: index out of range
│forcepoint-ngfw-docker.jfrog.io/robot/ctrl         version-20.ontoj││
goroutine 20206 [running]:rog.io/robot/ctrl         version-20.ontoj││PIDs: 2
github.com/jesseduffield/lazydocker/pkg/commands.(*Container).PlotGraph(0xc00043ad00, 0x0, 0x0, 0x0, 0x9c3c29, 0xa, 0x9ceacd, 0x1d, 0x9bf9b2, 0x5, ...)
│<none> /go/src/github.com/jesseduffield/lazydocker/pkg/commands/container_stats.go:241 +0x6dckB
github.com/jesseduffield/lazydocker/pkg/commands.(*Container).RenderStats(0xc00043ad00, 0x86, 0x0, 0x0, 0x0, 0x0)
│forcepo/go/src/github.com/jesseduffield/lazydocker/pkg/commands/container_stats.go:183 +0x1b6
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).renderContainerStats.func2(0xc00049aba0, 0xc00007fb00)
│forcepo/go/src/github.com/jesseduffield/lazydocker/pkg/gui/containers_panel.go:151 +0x4d
github.com/jesseduffield/lazydocker/pkg/tasks.(*TaskManager).NewTickerTask.func1(0xc00049aba0)15:26:29.674487354Z",
│forcepo/go/src/github.com/jesseduffield/lazydocker/pkg/tasks/tasks.go:101 +0x10dd": "2019-08-13T15:26:28.5592203Z",
github.com/jesseduffield/lazydocker/pkg/tasks.(*TaskManager).NewTask.func1.1(0xc000ceea80, 0xc00049aba0, 0xc0002f28c0, 0xc00049ac60)
│forcepo/go/src/github.com/jesseduffield/lazydocker/pkg/tasks/tasks.go:61 +0x34rrent": 2
created by github.com/jesseduffield/lazydocker/pkg/tasks.(*TaskManager).NewTask.func1
┌─Volume/go/src/github.com/jesseduffield/lazydocker/pkg/tasks/tasks.go:60 +0x19f_stats": {
```

I am at an old version:
```
Version: 0.6.3
Date: 2019-07-29T09:35:31Z
BuildSource: binaryRelease
Commit: c5996588d1657c0182a55af579b654e87d739ca6
OS: linux
Arch: amd64
```

But thought to re-post
